services:
  - type: web
    name: workshop-parts-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: tomtest0606@gmail.com
      - key: MAIL_PASSWORD
        value: rdtoyqqxoolahscc
      - key: MAIL_DEFAULT_SENDER
        value: tomtest0606@gmail.com
